### ISSUE TITLE
Spice of Fabric history-length Config

### ISSUE THREAD

**Issue by MissPotato** [thehobojoe/Progress#19]
The Spice of Fabric config is a bit misleading. The config node "history-length:" is actually your desired foods to cycle + 1. So, the pack is set to a history length of 9. Which means you actually need to juggle 10 food. The food containers only carry 9 food, and seeing as your config set history-length to 9, I'm assuming you wanted this to be the same.

Regardless, the food containers are useless anyways. The food containers only feed you the food with the highest hunger, even  if that food item is something you already ate in your food history. In other words, the food containers don't actually solve the issue of needing so many inventory slots just for food. This is an issue with Spice of Fabric tho. I have reported this to them already. https://github.com/Siphalor/spiceoffabric/issues/83

**Comment by MissPotato** [comment]
I also noticed the same issue with the health. If you want the SoF to provide an extra 20 health, you need to set the value to 40.

**Comment by thehobojoe** [comment]
> Regardless, the food containers are useless anyways. The food containers only feed you the food with the highest hunger, even if that food item is something you already ate in your food history.

This is not quite correct, the food container tries to feed you the food that best matches your current hunger need, regardless of if it's been eaten recently or not. If you're currently missing 2 food bars, and you have 2 foods that give you 8 hunger bars that you haven't eaten recently, and 1 food that gives you 2 hunger bars that you have eaten recently, it will choose the one food that gives you 2 hunger bars, because that most closely matches your missing hunger.

You're totally right about the history length however, and that was fixed in the most recent update. Thanks for the report 👍
