### ISSUE TITLE
Config for Spice of Life is really rough

### ISSUE THREAD

**Issue by MissPotato** [thehobojoe/Progress#21]
And by really rough, I mean literally not possible to achieve max health. To get to 20 hp you need to eat 4102 unique foods each time time you die. There is only around 490 food. Some are disabled and some aren't implemented in their mods.  The current system scales like this 2 food 1 hp, 4 food 2 hp, 8 food 3 hp, 16 food 4 hp, 32 food 5 hp. 64 food 6 hp. 128 food 7 hp, 256 food 8 hp, 512 food 9 hp - except you can't even get that much food. You only get 4 and a half hearts. (There does seem to be a little bit of weirdness with the rounding, as I was actually able to get 4 and a half hearts despite the math implying it is impossible after eeating every food in croptopia so about 300 foods in.) 

For my server I reworked the formula to be max HP at 200 foods. baseHealth + floor(uniqueFoodsEaten/10)

A bit annoying to get back to 40 hp after dying, as it takes (on average) 1.61 seconds per food that is 5 and a half minutes of eating animation.  Which I think was kind of your objective with the current config. 

Honestly tho, Spice of Life is really buggy in multiplayer. I wouldn't be upset seeing it removed entirely and replaced with something like https://www.curseforge.com/minecraft/mc-mods/nutritional-balance. Actually, that is  a forge mod. Seems like Spice of Fabric is the only hunger overhaul mod weh

**Comment by thehobojoe** [comment]
We've discussed this a bit on discord, but just to lay it out here - the spice of life config is set to provide an incentive for a few things
- Better foods (duh). Food mods add a lot of variety to the game, and without an incentive to use them, it's really wasted, because everyone just carries around a stack of bread or steak or whatever. Other kitcheny things like C4B also get a use here.
- More farms. This encourages both automation, which is really rewarding, and building (stylized or utilitarian), since those are the core of this pack I really want to push them wherever I can.
- Reward for staying alive. In MC there isn't much of a penalty for death, you have to do a corpse run and you lose some XP - in this we have graves so there's not even a risk of losing items. Losing hearts provides a big penalty for dying, and pushes players to engage more with the (many, and varied) tools that give the more strength and survivability.

I've hosted lots of servers with and without a food variety mod, and from my observations people build far more simple bases, and play for a much shorter amount of time when they're not present, *in spite of* the fact that many (or even most) players make vocal complaints about it. They build bigger bases, more automation, do more problem solving, and overall engage with the mods in the pack more, as food automation is fairly complex compared to many other things. Food variety mods that only add an incentive, not a downside, are not enough, people still just fall back to the stack of bread as their sole food source.

That said, there are lots of other frustrations with the spice of life mod outside of its core functionality. Like config issues, server sync issues, and the food container being very, very broken. I have some vague ideas about making my own, but that's TBD.
